before:
  hooks:
    - git reset --hard
    - git checkout .
builds:
  - id: api
    main: "./cmd/api/main.go"
    env:
      - CGO_ENABLED=0
  - id: observer
    main: "./cmd/observer/main.go"
    env:
      - CGO_ENABLED=0
  - id: syncmarkets
    main: "./cmd/syncmarkets/main.go"
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
