port: 8080
gin:
  mode: release

platforms:
#  - binance
#  - nimiq
#  - ripple

binance:
  api: https://testnet-dex.binance.org/api/v1

nimiq:
  rpc: http://localhost:8648

ripple:
  api: https://data.ripple.com/v2
